# General GLM settings

contrast_type: new_faces_vs_objects       # options: old_vs_new, pre_vs_post, etc.
smoothing_fwhm: 5            # in mm, null means no smoothing
height_control: bonferroni      # or fdr
p_value: 0.05                   # significance threshold
